### PR TITLE
SSL frontend correction

### LINKED ISSUE #66: SSL frontend issue with certs
I get the following error trying to use SSL frontend for "main" port in official traefik docker release:

```javascript
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x18 pc=0x639e40]

goroutine 9 [running]:
github.com/emilevauge/traefik/vendor/github.com/mailgun/manners.(*GracefulListener).Clone(0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/emilevauge/traefik/vendor/github.com/mailgun/manners/listener.go:105 +0x40
github.com/emilevauge/traefik/vendor/github.com/mailgun/manners.(*GracefulServer).HijackListener(0xc8200136c0, 0xc82016a360, 0x0, 0xc820142ff0, 0x0, 0x0)
	/go/src/github.com/emilevauge/traefik/vendor/github.com/mailgun/manners/server.go:184 +0x46
main.prepareServer(0xc82016d2c0, 0xc8200f5a20, 0xc8200136c0, 0xc8201d7eb0, 0x2, 0x2, 0x0)
	/go/src/github.com/emilevauge/traefik/traefik.go:235 +0x5a6
main.main.func1(0xc820016960, 0xc8200f5a20, 0xc8200240e8, 0xc8200240e0, 0xc8200240f8)
	/go/src/github.com/emilevauge/traefik/traefik.go:120 +0x7b6
created by main.main
	/go/src/github.com/emilevauge/traefik/traefik.go:133 +0xa0d

goroutine 1 [chan receive]:
main.main()
	/go/src/github.com/emilevauge/traefik/traefik.go:190 +0x148e

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [sleep]:
time.Sleep(0x3b9aca00)
	/usr/local/go/src/runtime/time.go:59 +0xf9
github.com/emilevauge/traefik/vendor/github.com/thoas/stats.New.func1(0xc820016840)
	/go/src/github.com/emilevauge/traefik/vendor/github.com/thoas/stats/stats.go:33 +0x2e
created by github.com/emilevauge/traefik/vendor/github.com/thoas/stats.New
	/go/src/github.com/emilevauge/traefik/vendor/github.com/thoas/stats/stats.go:35 +0x161

goroutine 18 [runnable]:
github.com/emilevauge/traefik/vendor/gopkg.in/fsnotify%2ev1.(*Watcher).readEvents(0xc82016c000)
	/go/src/github.com/emilevauge/traefik/vendor/gopkg.in/fsnotify.v1/inotify.go:159
created by github.com/emilevauge/traefik/vendor/gopkg.in/fsnotify%2ev1.NewWatcher
	/go/src/github.com/emilevauge/traefik/vendor/gopkg.in/fsnotify.v1/inotify.go:58 +0x315

goroutine 8 [select, locked to thread]:
runtime.gopark(0xc33aa8, 0xc820023728, 0xb0c888, 0x6, 0x45b318, 0x2)
	/usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc820023728, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc820023728)
	/usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 11 [runnable]:
main.main.func2(0x7f8338f27c98, 0xc82011f920, 0xc820016960)
	/go/src/github.com/emilevauge/traefik/traefik.go:169
created by main.main
	/go/src/github.com/emilevauge/traefik/traefik.go:174 +0x127d

goroutine 12 [runnable]:
main.main.func3(0xc8200169c0, 0xc8200240e0, 0xc820016a20)
	/go/src/github.com/emilevauge/traefik/traefik.go:177
created by main.main
	/go/src/github.com/emilevauge/traefik/traefik.go:183 +0x12d8

goroutine 13 [runnable]:
math/big.(*Int).Set(0xc820155470, 0xc8201554f0, 0xc8201554d0)
	/usr/local/go/src/math/big/int.go:66
math/big.(*Int).GCD(0xc8201555a8, 0xc82004bec0, 0x0, 0xc82004bde0, 0xc82004bdc0, 0x43e882)
	/usr/local/go/src/math/big/int.go:474 +0x37a
math/big.(*Int).ModInverse(0xc82004bec0, 0xc82004bde0, 0xc82004bdc0, 0xc82004bea0)
	/usr/local/go/src/math/big/int.go:578 +0x61
crypto/rsa.(*PrivateKey).Precompute(0xc820016e40)
	/usr/local/go/src/crypto/rsa/rsa.go:413 +0x220
crypto/x509.ParsePKCS1PrivateKey(0xc82013c500, 0x4a7, 0x4a7, 0xc820016e40, 0x0, 0x0)
	/usr/local/go/src/crypto/x509/pkcs1.go:81 +0x6f4
crypto/tls.parsePrivateKey(0xc82013c500, 0x4a7, 0x4a7, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/tls.go:255 +0x6e
crypto/tls.X509KeyPair(0xc8200a5cb4, 0x0, 0x200, 0xc82007788b, 0x0, 0x200, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/crypto/tls/tls.go:214 +0x499
crypto/tls.LoadX509KeyPair(0xc82004b5c0, 0x14, 0xc82004b620, 0x13, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/crypto/tls/tls.go:179 +0x1bf
github.com/emilevauge/traefik/vendor/github.com/mailgun/manners.(*GracefulServer).ListenAndServeTLS(0xc8200136c0, 0xc82004b5c0, 0x14, 0xc82004b620, 0x13, 0x0, 0x0)
	/go/src/github.com/emilevauge/traefik/vendor/github.com/mailgun/manners/server.go:152 +0x255
main.startServer(0xc8200136c0, 0xc8200f5a20)
	/go/src/github.com/emilevauge/traefik/traefik.go:197 +0x177
created by main.main
	/go/src/github.com/emilevauge/traefik/traefik.go:188 +0x146b

goroutine 19 [select]:
main.(*FileProvider).Provide.func1(0xc82016c000, 0xc820144008, 0xc82004b840, 0xc820016960)
	/go/src/github.com/emilevauge/traefik/file.go:37 +0x5eb
created by main.(*FileProvider).Provide
	/go/src/github.com/emilevauge/traefik/file.go:50 +0x44c
```

I use file backend and same certs work for api [web] port.
Also same configuration with same certs is working on other server, difference is other server uses image from 2 weeks ago and new one image from 2 hours ago.

### PR DESCRIPTION
**Pull request by emilevauge**
This PR corrects SSL support in frontends using Manners.
Fixes #66

### CODE REVIEW

File: traefik.go [hunk 1]
```diff
@@ -247,21 +268,32 @@ func prepareServer(router *mux.Router, globalConfiguration *GlobalConfiguration,
 	negroni.UseHandler(router)
 
 	if oldServer == nil {
+		tlsConfig, err := createTLSConfig(globalConfiguration.CertFile, globalConfiguration.KeyFile)
```
Comment (vdemeester) [inline traefik.go]: You could bring that up (before `if oldServer ==nil`), as you do exactly the same it in the `if` and in the `else`.

Comment (emilevauge) [inline traefik.go]: Absolutely, fixed.

**Comment by vdemeester** [comment]
LGTM 🐯
